x509_crt_bundle error
Error: x509_crt_bundle not found.
Due to a certificat expiration
https://github.com/espressif/esp-idf/issues/7621#issue-1012039784
PlatformIO tab (on the left), Project Tasks > esp32dev > Platform > Run Menuconfig
Then: Component config > mbedTLS > Certificate Bundle->Enable trusted root certificate bundle
Deactivate the option.